-- structure
CREATE TABLE "Albums" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"ArtistId"	INTEGER NOT NULL,
	"Title"	TEXT NOT NULL,
	"NamedTitle"	TEXT NOT NULL,
	"Year"	INTEGER NOT NULL,
	"Description"	TEXT NOT NULL,
	"Rating"	REAL NOT NULL,
	"IsListened"	TEXT NOT NULL DEFAULT 'false',
	"IsFavorite"	TEXT NOT NULL DEFAULT 'false',
	"Created"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "ArtistGenres" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"ArtistId"	INTEGER NOT NULL,
	"Genre"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "ArtistTypes" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"ArtistId"	INTEGER NOT NULL,
	"Type"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "Artists" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MediaTypeSourceId"	INTEGER NOT NULL,
	"MediaTypeId"	INTEGER NOT NULL,
	"ArtistNamedName"	TEXT NOT NULL,
	"ArtistName"	TEXT NOT NULL,
	"MusicBrainzArtistID"	TEXT NOT NULL,
	"Formed"	TEXT NOT NULL,
	"FormedIn"	TEXT NOT NULL,
	"Biography"	TEXT NOT NULL,
	"VideoClipLink"	TEXT,
	"IsDisbanded"	TEXT NOT NULL DEFAULT 'false',
	"IsListened"	TEXT NOT NULL DEFAULT 'false',
	"IsFavorite"	TEXT NOT NULL DEFAULT 'false',
	"Created"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "BandMembers" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"ArtistId"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Role"	TEXT NOT NULL,
	"Order"	INTEGER NOT NULL,
	"Thumb"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "EpisodeActors" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"EpisodeId"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Role"	TEXT NOT NULL,
	"Order"	INTEGER NOT NULL,
	"Thumb"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "EpisodeCredits" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"EpisodeId"	INTEGER NOT NULL,
	"Credit"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "EpisodeGenre" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"EpisodeId"	INTEGER NOT NULL,
	"Genre"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "EpisodeRatings" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"EpisodeId"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Max"	INTEGER NOT NULL,
	"Value"	REAL NOT NULL,
	"Votes"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "Episodes" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TvShowId"	INTEGER NOT NULL,
	"SeasonId"	INTEGER NOT NULL,
	"Title"	TEXT NOT NULL,
	"NamedTitle"	TEXT NOT NULL,
	"Episode"	INTEGER NOT NULL,
	"Synopsis"	TEXT NOT NULL,
	"Runtime"	INTEGER NOT NULL,
	"MPAA"	TEXT NOT NULL,
	"LastPlayed"	TEXT NOT NULL,
	"ImDbId"	TEXT NOT NULL,
	"TvDbId"	INTEGER,
	"TmDbId"	INTEGER,
	"Director"	TEXT,
	"Year"	INTEGER NOT NULL,
	"Aired"	TEXT NOT NULL,
	"IsWatched"	TEXT NOT NULL DEFAULT 'false',
	"IsFavorite"	TEXT NOT NULL DEFAULT 'false',
	"Created"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MediaTypeSources" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MediaTypeId"	INTEGER NOT NULL,
	"MediaSourcePath"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MediaTypes" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MediaName"	TEXT NOT NULL,
	"MediaType"	TEXT,
	"IsMedia"	TEXT NOT NULL DEFAULT 'false',
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieActors" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Role"	TEXT NOT NULL,
	"Order"	INTEGER NOT NULL,
	"Thumb"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieAudioInfo" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Codec"	TEXT,
	"Language"	TEXT,
	"Channels"	INTEGER,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieCountry" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Country"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieCredits" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Credit"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieDirectors" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Director"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieFileInfo" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieGenre" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Genre"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieRatings" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Max"	INTEGER NOT NULL,
	"Value"	REAL NOT NULL,
	"Votes"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieResume" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Position"	INTEGER NOT NULL,
	"Total"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieStreamDetails" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieSubtitles" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Language"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieTags" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Tag"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "MovieVideoInfo" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MovieId"	INTEGER NOT NULL,
	"Codec"	TEXT,
	"Aspect"	REAL,
	"Width"	INTEGER,
	"Height"	INTEGER,
	"Is3D"	TEXT NOT NULL DEFAULT 'false',
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "Movies" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MediaTypeSourceId"	INTEGER NOT NULL,
	"MediaTypeId"	INTEGER NOT NULL,
	"MovieTitle"	TEXT NOT NULL,
	"OriginalTitle"	TEXT NOT NULL,
	"NamedTitle"	TEXT NOT NULL,
	"Synopsis"	TEXT,
	"Tagline"	TEXT,
	"Runtime"	INTEGER NOT NULL,
	"MPAA"	TEXT,
	"LastPlayed"	TEXT NOT NULL,
	"ImDbId"	TEXT NOT NULL,
	"TmDbId"	INTEGER,
	"Set"	TEXT,
	"Premiered"	TEXT NOT NULL,
	"IsEnded"	TEXT NOT NULL DEFAULT 'false',
	"Studio"	TEXT,
	"Trailer"	TEXT,
	"TvShowLink"	TEXT,
	"IsWatched"	TEXT NOT NULL DEFAULT 'false',
	"IsFavorite"	TEXT NOT NULL DEFAULT 'false',
	"Created"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "Seasons" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TvShowId"	INTEGER NOT NULL,
	"SeasonNumber"	INTEGER NOT NULL,
	"SeasonName"	TEXT NOT NULL,
	"Year"	INTEGER NOT NULL,
	"IsWatched"	TEXT NOT NULL DEFAULT 'false',
	"IsFavorite"	TEXT NOT NULL DEFAULT 'false',
	"Synopsis"	TEXT NOT NULL,
	"Premiered"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "Songs" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"ArtistId"	INTEGER NOT NULL,
	"AlbumId"	INTEGER NOT NULL,
	"Title"	TEXT NOT NULL,
	"NamedTitle"	TEXT NOT NULL,
	"Rating"	REAL NOT NULL,
	"Length"	INTEGER NOT NULL,
	"AlbumOrder"	INTEGER NOT NULL,
	"IsListened"	TEXT NOT NULL DEFAULT 'false',
	"IsFavorite"	TEXT NOT NULL DEFAULT 'false',
	"Created"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "TvShowActors" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TvShowId"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Role"	TEXT NOT NULL,
	"Order"	INTEGER NOT NULL,
	"Thumb"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "TvShowGenre" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TvShowId"	INTEGER NOT NULL,
	"Genre"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "TvShowRatings" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TvShowId"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Max"	INTEGER NOT NULL,
	"Value"	REAL NOT NULL,
	"Votes"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "TvShowResume" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TvShowId"	INTEGER NOT NULL,
	"SeasonId"	INTEGER NOT NULL,
	"EpisodeId"	INTEGER NOT NULL,
	"Position"	INTEGER NOT NULL,
	"Total"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "TvShows" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"MediaTypeSourceId"	INTEGER NOT NULL,
	"MediaTypeId"	INTEGER NOT NULL,
	"TvShowNamedTitle"	TEXT NOT NULL,
	"TvShowTitle"	TEXT NOT NULL,
	"NumberOfSeasons"	INTEGER DEFAULT 0,
	"NumberOfEpisodes"	INTEGER DEFAULT 0,
	"Synopsis"	TEXT,
	"TagLine"	TEXT,
	"Runtime"	INTEGER NOT NULL,
	"MPAA"	TEXT,
	"LastPlayed"	TEXT NOT NULL,
	"Aired"	TEXT NOT NULL,
	"ImDbId"	TEXT NOT NULL,
	"TvDbId"	INTEGER,
	"TmDbId"	INTEGER,
	"IsEnded"	TEXT NOT NULL DEFAULT 'false',
	"Trailer"	TEXT,
	"Studio"	TEXT,
	"IsWatched"	TEXT NOT NULL DEFAULT 'false',
	"IsFavorite"	TEXT NOT NULL DEFAULT 'false',
	"Created"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE "Users" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Username"	TEXT NOT NULL,
	"Password"	TEXT NOT NULL,
	"SecurityQuestion"	TEXT NOT NULL,
	"SecurityAnswer"	TEXT NOT NULL,
	"Created"	TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("Id" AUTOINCREMENT)
);

-- indexing

CREATE UNIQUE INDEX "EpisodeActors_Idx" ON "EpisodeActors" (
	"Id"	ASC,
	"EpisodeId"	ASC
);
CREATE UNIQUE INDEX "EpisodeCredits_Idx" ON "EpisodeCredits" (
	"Id"	ASC,
	"EpisodeId"	ASC
);
CREATE UNIQUE INDEX "EpisodeGenre_Idx" ON "EpisodeGenre" (
	"Id"	ASC,
	"EpisodeId"	ASC
);
CREATE UNIQUE INDEX "EpisodeRatings_Idx" ON "EpisodeRatings" (
	"Id"	ASC,
	"EpisodeId"	ASC
);
CREATE UNIQUE INDEX "Episodes_Idx" ON "Episodes" (
	"Id"	ASC,
	"TvShowId"	ASC,
	"SeasonId"	ASC
);
CREATE UNIQUE INDEX "Seasons_Idx" ON "Seasons" (
	"Id"	ASC,
	"TvShowId"	ASC
);
CREATE UNIQUE INDEX "TvShowActors_Idx" ON "TvShowActors" (
	"Id"	ASC,
	"TvShowId"	ASC
);
CREATE UNIQUE INDEX "TvShowGenre_Idx" ON "TvShowGenre" (
	"Id"	ASC,
	"TvShowId"	ASC
);
CREATE UNIQUE INDEX "TvShowRatings_Idx" ON "TvShowRatings" (
	"Id"	ASC,
	"TvShowId"	ASC
);
CREATE UNIQUE INDEX "TvShows_Idx" ON "TvShows" (
	"Id"	ASC
);
